User.create!(username:"username", email:"email", password:"password", avatar:"fsp_icons_0003_Layer-0.png", work:"Artist at ___")
User.create!(username:"Up Grade", email:"crowman@email.com", password:"you'llneverguess", avatar:"fsp_icons_0004_Layer-5.png", work:"2D Artist at Zomb Studio")
User.create!(username:"xX_PenGod_Xx", email:"artweewoo@art.com", password:"iluvart", avatar:"fsp_icons_0016_Layer-17.png", work:"3D Artist at Obo Studios")
User.create!(username:"LazorBen", email:"pewpew1337@gmail.com", password:"i shoot therefore I pew", avatar:"fsp_icons_0000_Layer-4.png", work:"Artist at Home")
User.create!(username:"itsSamanthine", email:"samzar@snailmail.com", password:"enihtnamassti", avatar:"fsp_icons_0001_Layer-3.png", work: "Artist at Homework Schoolio")
User.create!(username:"aBoUtTiMe", email:"sPelLiNgAlTeRnAtInGcApSiShArD@mail.com", password:"but this one's all lowercase", avatar:"fsp_icons_0006_Layer-7.png", work:"3D Artist at University of Idaho")
User.create!(username:"NotAboutIt", email:"imNotAboutIt@gmail.com", password:"what about it!@", avatar:"fsp_icons_0003_Layer-1.png", work:"Artist at AE ICED")
User.create!(username:"A_is_for_fAngus", email:"beefboi@email.com", password:"babyBacccRibs", avatar:"fsp_icons_0004_Layer-5.png", work:"Artist at JV3")
User.create!(username:"TRI_ART", email:"ArtaRtarT@email.com", password:"secret zelda reference", avatar:"fsp_icons_0002_Layer-2.png", work:"Tech Artist at Armarzorn LTE")
# User.create!(username:"", email:"", password:"", avatar:"")

