User.create!(username:"User Name", email:"demoemail", password:"password", avatar:"fsp_icons_0003_Layer-0.png", work:"Artist at ___")
User.create!(username:"Up Grade", email:"upGrade@email.com", password:"you'llneverguess", avatar:"fsp_icons_0004_Layer-5.png", work:"2D Artist at Zomb Studio")
User.create!(username:"xX_Pen God_Xx", email:"artweewoo@art.com", password:"iluvart", avatar:"fsp_icons_0016_Layer-17.png", work:"3D Artist at Obo Studios")
User.create!(username:"Ben Laser", email:"ben_pewpew@gmail.com", password:"i shoot therefore I pew", avatar:"fsp_icons_0000_Layer-4.png", work:"Artist at Home")
User.create!(username:"Robert Artman", email:"robzar@snailmail.com", password:"enihtnamassti", avatar:"fsp_icons_0001_Layer-3.png", work: "Artist at Homework Schoolio")
User.create!(username:"Samuel Cramin", email:"sam_cram@mail.com", password:"but this one's all lowercase", avatar:"fsp_icons_0006_Layer-7.png", work:"3D Artist at University of Idaho")
User.create!(username:"Samantha Floresh", email:"SamFlo@gmail.com", password:"what about it!@", avatar:"fsp_icons_0003_Layer-1.png", work:"Artist at AE ICED")
User.create!(username:"Crom McGoblin", email:"CromGoblin@email.com", password:"babyBacccRibs", avatar:"fsp_icons_0004_Layer-5.png", work:"Artist at JV3")
User.create!(username:"Art Man", email:"artman@email.com", password:"secret zelda reference", avatar:"fsp_icons_0002_Layer-2.png", work:"Tech Artist at Armarzorn LTE")
# User.create!(username:"", email:"", password:"", avatar:"")

