Art.create!(artist_id: 1, title:"Bag Head", description:"Made a character out of a berlap sack full of beans. Just one of the renders from a super short animation. Maya is hard. Have a nice day.", url:"/images/arts/baghead2.PNG")
Art.create!(artist_id: 2, title:"If Fly Traps Could Run", description:"Testing out Scupltris. It's pretty floppy for a sculpting software but it's free so beginners rejoice. Going back to Zbrush", url:"/images/arts/Kalvin2.PNG")
Art.create!(artist_id: 3, title:"Disaster Piece", description:"Tiny diorama of earthquake aftermath. Still learning materials", url:"/images/arts/DistasterPiece.png")
Art.create!(artist_id: 4, title:"Bringeth Mine Gold", description:"", url:"/images/arts/napkinartkremlin.JPG")
Art.create!(artist_id: 5, title:"Shoe Recreation", description:"Modeled from one reference image. Saw this as a good opportunity to pick up spline tools. Really helps nail the shoe's contours. Modeled in 3DSMax and materials in Substance Painter", url:"/images/arts/objectrecreation1.JPG")
Art.create!(artist_id: 6, title:"Snowman Assignment Final Version 1", description:"Hello I'm new to artstation just stopping by", url:"/images/arts/SnowmanRender1.PNG")
# Art.create!(artist_id: , title:"", description:"", url:"app/assets/images/arts/2AbTool.jpg")
# Art.create!(artist_id: , title:"", description:"", url:"app/assets/images/arts/baghead2.PNG")
# Art.create!(artist_id: , title:"", description:"", url:"app/assets/images/arts/blueguybreakswall.jpg")
# Art.create!(artist_id: , title:"", description:"", url:"app/assets/images/arts/Board.jpg")
# Art.create!(artist_id: , title:"", description:"", url:"app/assets/images/arts/BoltActionRifleUVWunrapmap2.PNG")
# Art.create!(artist_id: , title:"", description:"", url:"app/assets/images/arts/Bottles&Wineglasses.PNG")
# Art.create!(artist_id: , title:"", description:"", url:"app/assets/images/arts/Catapult.gif")
# Art.create!(artist_id: , title:"", description:"", url:"app/assets/images/arts/coffeebacon.gif")
# Art.create!(artist_id: , title:"", description:"", url:"app/assets/images/arts/CrateStorageMilitary.png")
# Art.create!(artist_id: , title:"", description:"", url:"app/assets/images/arts/CrateStorageMilitaryRender.PNG")
# Art.create!(artist_id: , title:"", description:"", url:"app/assets/images/arts/day1concept.PNG")
# Art.create!(artist_id: , title:"", description:"", url:"app/assets/images/arts/DistasterPiece.png")
# Art.create!(artist_id: , title:"", description:"", url:"app/assets/images/arts/googlebrushart.JPG")
# Art.create!(artist_id: , title:"", description:"", url:"app/assets/images/arts/Headset 2.png")
# Art.create!(artist_id: , title:"", description:"", url:"app/assets/images/arts/InteriorFinalRender.png")
# Art.create!(artist_id: , title:"", description:"", url:"app/assets/images/arts/jetgreybox.png")
# Art.create!(artist_id: , title:"", description:"", url:"app/assets/images/arts/Kalvin and rock creature.PNG")
# Art.create!(artist_id: , title:"", description:"", url:"app/assets/images/arts/Kalvin.png")
# Art.create!(artist_id: , title:"", description:"", url:"app/assets/images/arts/Kalvin2.PNG")
# Art.create!(artist_id: , title:"", description:"", url:"app/assets/images/arts/KalvinTest.png")
# Art.create!(artist_id: , title:"", description:"", url:"app/assets/images/arts/lizardman.jpg")
# Art.create!(artist_id: , title:"", description:"", url:"app/assets/images/arts/Mech full 2.PNG")
# Art.create!(artist_id: , title:"", description:"", url:"app/assets/images/arts/napkinart.PNG")
# Art.create!(artist_id: , title:"", description:"", url:"app/assets/images/arts/napkinartkremlin.JPG")
# Art.create!(artist_id: , title:"", description:"", url:"app/assets/images/arts/objectrecreation1.JPG")
# Art.create!(artist_id: , title:"", description:"", url:"app/assets/images/arts/planetbullet.png")
# Art.create!(artist_id: , title:"", description:"", url:"app/assets/images/arts/progress2.png")
# Art.create!(artist_id: , title:"", description:"", url:"app/assets/images/arts/RailCar2.PNG")
# Art.create!(artist_id: , title:"", description:"", url:"app/assets/images/arts/roomRemodel.PNG")
# Art.create!(artist_id: , title:"", description:"", url:"app/assets/images/arts/RSIWIPShip.PNG")
# Art.create!(artist_id: , title:"", description:"", url:"app/assets/images/arts/RulebookCover.jpg")
# Art.create!(artist_id: , title:"", description:"", url:"app/assets/images/arts/RulebookInsideCoverPages1&6.jpg")
# Art.create!(artist_id: , title:"", description:"", url:"app/assets/images/arts/RulebookPages2&5.jpg")
# Art.create!(artist_id: , title:"", description:"", url:"app/assets/images/arts/RulebookPages3&4.jpg")
# Art.create!(artist_id: , title:"", description:"", url:"app/assets/images/arts/selfportrait.PNG")
# Art.create!(artist_id: , title:"", description:"", url:"app/assets/images/arts/Shrog3.PNG")
# Art.create!(artist_id: , title:"", description:"", url:"app/assets/images/arts/SnowmanRender1.PNG")
# Art.create!(artist_id: , title:"", description:"", url:"app/assets/images/arts/Speeder model final.PNG")
# Art.create!(artist_id: , title:"", description:"", url:"app/assets/images/arts/Speeder Speed Racer.PNG")
# Art.create!(artist_id: , title:"", description:"", url:"app/assets/images/arts/spikymobilebase.png")
# Art.create!(artist_id: , title:"", description:"", url:"app/assets/images/arts/SS Vehicle 1.PNG")
# Art.create!(artist_id: , title:"", description:"", url:"app/assets/images/arts/terracatta.JPG")
# Art.create!(artist_id: , title:"", description:"", url:"app/assets/images/arts/tree_foliage.JPG")
# Art.create!(artist_id: , title:"", description:"", url:"app/assets/images/arts/unity scene.PNG")
# Art.create!(artist_id: , title:"", description:"", url:"app/assets/images/arts/vrpgCharSilhouette2.jpg")
# Art.create!(artist_id: , title:"", description:"", url:"app/assets/images/arts/World Map.jpg")
# Art.create!(artist_id: , title:"", description:"", url:"app/assets/images/arts/zombie1.PNG")
# Art.create!(artist_id: , title:"", description:"", url:"app/assets/images/arts/zombie2.PNG")
# Art.create!(artist_id: , title:"", description:"", url:"app/assets/images/arts/zombiecakes.PNG")
# Art.create!(artist_id: , title:"", description:"", url:"app/assets/images/arts/ZombieIteration1.PNG")
# Art.create!(artist_id: , title:"", description:"", url:"app/assets/images/arts/ZombieIteration2.PNG")
# Art.create!(artist_id: , title:"", description:"", url:"app/assets/images/arts/ZombieIteration3.PNG")

# Art.create!(artist_id: , title:"", description:"", url:"")