Tag.create!(name: "Digital 2D", category: "Medium")
Tag.create!(name: "Digital 3D", category: "Medium")
Tag.create!(name: "Animation", category: "Medium")
Tag.create!(name: "Real-time", category: "Medium")
Tag.create!(name: "Live Action CG/VFX", category: "Medium")
Tag.create!(name: "3D Printing", category: "Medium")
Tag.create!(name: "Traditional Ink", category: "Medium")
Tag.create!(name: "Traditional Dry Media", category: "Medium")
Tag.create!(name: "Traditional Paint", category: "Medium")
Tag.create!(name: "Traditional Sculpture", category: "Medium")
Tag.create!(name: "Mixed Media", category: "Medium")

Tag.create!(name: "Abstract", category: "Subject Matter")
Tag.create!(name: "Anatomy", category: "Subject Matter")
Tag.create!(name: "Animals & Wildlife", category: "Subject Matter")
Tag.create!(name: "Anime & Manga", category: "Subject Matter")
Tag.create!(name: "Architectural Concepts", category: "Subject Matter")
Tag.create!(name: "Architectural Visualization", category: "Subject Matter")
Tag.create!(name: "Automotive", category: "Subject Matter")
Tag.create!(name: "Board & Card Game Art", category: "Subject Matter")
Tag.create!(name: "Book Illustration", category: "Subject Matter")
Tag.create!(name: "Character Animation", category: "Subject Matter")
Tag.create!(name: "Character Design", category: "Subject Matter")
Tag.create!(name: "Character Modeling", category: "Subject Matter")
Tag.create!(name: "Children's Art", category: "Subject Matter")
Tag.create!(name: "Comic Art", category: "Subject Matter")
Tag.create!(name: "Concept Art", category: "Subject Matter")
Tag.create!(name: "Cover Art", category: "Subject Matter")
Tag.create!(name: "Creatures", category: "Subject Matter")
Tag.create!(name: "Editorial Illustration", category: "Subject Matter")
Tag.create!(name: "Environmental Concept Art & Design", category: "Subject Matter")
Tag.create!(name: "Fan Art", category: "Subject Matter")
Tag.create!(name: "Fantasy", category: "Subject Matter")
Tag.create!(name: "Fashion & Costume Design", category: "Subject Matter")
Tag.create!(name: "Game Art", category: "Subject Matter")
Tag.create!(name: "Gameplay & Level Design", category: "Subject Matter")
Tag.create!(name: "Games and Real-Time 3D Environment Art", category: "Subject Matter")
Tag.create!(name: "Graphic Design", category: "Subject Matter")
Tag.create!(name: "Hard Surface", category: "Subject Matter")
Tag.create!(name: "Horror", category: "Subject Matter")
Tag.create!(name: "Illustrastion", category: "Subject Matter")
Tag.create!(name: "Industrial & Product Design", category: "Subject Matter")
Tag.create!(name: "Lighting", category: "Subject Matter")
Tag.create!(name: "Matte Painting", category: "Subject Matter")
Tag.create!(name: "Mecha", category: "Subject Matter")
Tag.create!(name: "Mechanical Design", category: "Subject Matter")
Tag.create!(name: "Motion Graphics", category: "Subject Matter")
Tag.create!(name: "Photogrammetry & 3D Scanning", category: "Subject Matter")
Tag.create!(name: "Pixel and Voxel Art", category: "Subject Matter")
Tag.create!(name: "Portraits", category: "Subject Matter")
Tag.create!(name: "Props", category: "Subject Matter")
Tag.create!(name: "Realism", category: "Subject Matter")
Tag.create!(name: "Science Fiction", category: "Subject Matter")
Tag.create!(name: "Scientific Illustration & Visualization", category: "Subject Matter")
Tag.create!(name: "Scripts & Tools", category: "Subject Matter")
Tag.create!(name: "Sketches", category: "Subject Matter")
Tag.create!(name: "Still Life", category: "Subject Matter")
Tag.create!(name: "Storyboards", category: "Subject Matter")
Tag.create!(name: "Stylized", category: "Subject Matter")
Tag.create!(name: "Technical Art", category: "Subject Matter")
Tag.create!(name: "Textures & Materials", category: "Subject Matter")
Tag.create!(name: "Toys & Collectibles", category: "Subject Matter")
Tag.create!(name: "Tutorials", category: "Subject Matter")
Tag.create!(name: "User Interface (UI) Art", category: "Subject Matter")
Tag.create!(name: "Vehicles", category: "Subject Matter")
Tag.create!(name: "VFX for Film, TV & Animation", category: "Subject Matter")
Tag.create!(name: "VFX for Real-Time & Games", category: "Subject Matter")
Tag.create!(name: "Virtual and Augmented Reality", category: "Subject Matter")
Tag.create!(name: "Visual Development", category: "Subject Matter")
Tag.create!(name: "Weapons", category: "Subject Matter")
Tag.create!(name: "Web and App Design", category: "Subject Matter")