# Art.create!(artist_id: , title:"", description:"", url:"")
Art.create!(artist_id: 1, title:"Bag Head", description:"Made a character out of a berlap sack full of beans. Just one of the renders from a super short animation. Maya is hard. Have a nice day.", url:"/images/arts/baghead2.PNG")
Art.create!(artist_id: 2, title:"If Fly Traps Could Run", description:"Testing out Scupltris. It's pretty floppy for a sculpting software but it's free so beginners rejoice. Going back to Zbrush", url:"/images/arts/Kalvin2.PNG")
Art.create!(artist_id: 3, title:"Disaster Piece", description:"Tiny diorama of earthquake aftermath. Still learning materials", url:"/images/arts/DistasterPiece.png")
Art.create!(artist_id: 4, title:"Bringeth Mine Gold", description:"", url:"/images/arts/napkinartkremlin.JPG")
Art.create!(artist_id: 5, title:"Shoe Recreation", description:"Modeled from one reference image. Saw this as a good opportunity to pick up spline tools. Really helps nail the shoe's contours. Modeled in 3DSMax and materials in Substance Painter", url:"/images/arts/objectrecreation1.JPG")
Art.create!(artist_id: 6, title:"Snowman Assignment Final Version 1", description:"Hello I'm new to artstation just stopping by", url:"/images/arts/SnowmanRender1.PNG")
